version: '3'
services: 
  downloader:
    build: 
      context: .
      dockerfile: Dockerfile.downloader
    env_file:
      - env/downloader.env
    volumes:
      - downloads:/tmp/downloads:rw
      - ./downloader:/app:rw
      - /app/node_modules
  
  search:
    build: 
      context: .
      dockerfile: Dockerfile.search
    volumes:
      - ./search:/app:rw
      - /app/node_modules
  
  slackbot:
    build: 
      context: .
      dockerfile: Dockerfile.slackbot
    volumes:
      - ./slackbot:/app:rw
      - /app/node_modules

volumes: 
  downloads: {}