version: '3'
services: 
  irc:
    build: 
      context: .
      dockerfile: Dockerfile.downloader
    env_file:
      - env/downloader.env
    volumes:
      - ./downloads:/tmp/downloads:rw
      - ./downloader:/app:rw
      - /app/node_modules
  
  client:
    image: library/irssi:latest